### ISSUE TITLE
Core/Base -> Kein Ram verfügbar obwohl genug frei wäre

### ISSUE THREAD

**Issue by Lasergott** [TimoCloud/TimoCloud-5#13]
Der Core sagt das, fast kein BASE Ram mehr vorhanden ist, obwohl alle GameServer offline sind und der eigentliche Server noch genug Ram frei hat. Beim core neustart wird der eigentliche Ram Verbrauch wieder richtig angezeigt.

**Comment by TimoZikeli** [comment]
In English, please

**Comment by Lasergott** [comment]
The Core says that there is almost no BASE Ram left, although all GameServer are offline and the actual server still has enough Ram free. When core reboot the actual Ram consumption is displayed correctly again. (Hm, why i have to write in english? You are german...?)
