### ISSUE TITLE
Signs -> PlayerInteractEvent -> NullPointerException

### ISSUE THREAD

**Issue by Lasergott** [TimoCloud/TimoCloud-5#14]
If a sign / server is offline and you try to click it, the console will show a NullPointer NullPointerException.

Error Log ->
https://paste.timo.cloud/nejihihono.vbs

**Comment by TimoZikeli** [comment]
How does it happen that a sign shows an offline server?
When it is specified statically?

**Comment by Lasergott** [comment]
No, different. If a sign is empty, this mistake comes. (Empty = The sign is not used by any server)

**Comment by Lasergott** [comment]
Was fixed in the last update
