### ISSUE TITLE
Bug through multi-time restart

### ISSUE THREAD

**Issue by HaAdrian** [TimoCloud/TimoCloud-5#15]
Good evening,

if you restart a server several times in a row through the core, this error is emitted every second:

![error](https://user-images.githubusercontent.com/28960799/37879536-cba701ba-307a-11e8-915f-355467b61a5f.png)

Kind regards
Adrian

**Comment by TimoZikeli** [comment]
Could you please provide the whole log?

**Comment by HaAdrian** [comment]
Here is the whole log:

[2018-03-24-6.log](https://github.com/TimoCloud/TimoCloud/files/1847106/2018-03-24-6.log)

(But I would have a suggestion if you can't fix this error. You could install a delay in the 'restart <Server/Proxy>' command so that multiple restarts are no longer possible)
