### ISSUE TITLE
Group priorities don't affect server startup order

### ISSUE THREAD

**Issue by ghost** [TimoCloud/TimoCloud-5#16]
It seems like priorities have no effect on server startup order.

**Comment by TimoZikeli** [comment]
Do you have proof for that? (Configs and core log)

**Comment by ghost** [comment]
https://pastebin.com/gKsDh49D

Switching the lobby's and the other server's priorities does not change server startup order either.

**Comment by TimoZikeli** [comment]
At first, please don‘t use priority 0. The priority is getting multiplied by the amount of needed servers. So you‘ll always get 0.
Secondly, static servers will get started first, then the temporary ones. Could you please change your config to values of at least 1 and send the core‘s output again?
Thanks!

**Comment by ghost** [comment]
the priority is sometimes reset... so I can't do anything against that.

**Comment by TimoZikeli** [comment]
Please give us some information on that.
