### ISSUE TITLE
When restarting a group, the temp folder is not cleared

### ISSUE THREAD

**Issue by ghost** [TimoCloud/TimoCloud-5#17]
Folders of closed temporary servers are not deleted when using /restart or /timocloud restart <group>

**Comment by TimoZikeli** [comment]
They are, but with a delay of a minute or so. Can you confirm that?

**Comment by ghost** [comment]
Can't confirm that sadly, server folders are not deleted even after multiple minutes have passed.
Though, after looking through older undeleted folders, I noticed that they're half-empty. It looks like theyre only partially deleted.

**Comment by TimoZikeli** [comment]
Fixed in 222b9a9c6f989071bac174cefd5645367388f657
