### ISSUE TITLE
Libraries for TimoCloud

### ISSUE THREAD

**Issue by katzendrama** [TimoCloud/TimoCloud-5#6]
Hello, I need the libraries for TimoCloud, I found out that I need: 
Apache Commons JAR
BungeeCord JAR
Spigot JAR

And the Classes which I have not found online:
org.json.simple
com.fasterxml.jackson
com.google.common.io
io.netty
org.jline

Can someone please tell me all the JAR file names?

**Comment by TimoZikeli** [comment]
Hi,
please don't build TimoCloud manually - it's a Maven project and you can just run `mvn install` to build it.

Kind regards,
Timo
