### ISSUE TITLE
TimoCloudBungee wird nicht komplett geladen

### ISSUE THREAD

**Issue by gregorherr** [TimoCloud/TimoCloud-5#7]
Hey,
seid der Version 5.0.6 habe ich das Problem, dass der Bungee nicht komplett den Startup durchführt. 
Ich habe alle anderen Plugins probehalber mal entfernt und der Fehler tritt trotzdem auf. 
Es kommt kein direkter Fehler, allerdings fehlt im Log die Nachricht, dass TimoCloud erfolgreich enabled wurde, wenn ich das im Source richtig erkannt habe.

Bungee: https://hastebin.com/oreyofohid.sql
Core: https://hastebin.com/qiwofiyuhe.rb
Cord: https://hastebin.com/zibabufina.rb
Base: https://hastebin.com/umevicotab.rb

Komischerweise gibt es selten (bisher einmal) Fälle, wo dieses nicht auftritt.

  ~nauz

**Comment by TimoZikeli** [comment]
Fixed in #v5.0.7
